apiVersion: "v1"
kind: "BuildConfig"
metadata:
  name: "win-python-build"
spec:
  nodeSelector:
    kubernetes.io/arch: amd64
    kubernetes.io/os: windows
    node.kubernetes.io/windows-build: 10.0.17763  
  output:
    to:
      kind: ImageStreamTag
      name: windows-pyton-app1:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: python:windowsservercore
    type: Source
  successfulBuildsHistoryLimit: 5  
